name: mrinr2
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python[version='<3.12']
  - simpleitk
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - scipy
  - matplotlib
  - seaborn
  - ubelt
  - cloudpickle
  - docker-py
  - dill
  - dipy
  - icecream
  - ipdb
  - isort
  - ipywidgets
  - ipympl
  - jupyter
  - jupytext
  - nbstripout
  - networkx
  - numba
  - pre-commit
  - python-box
  - pytz
  - pytransform3d
  - tqdm
  - toolz
  - watermark
  - boltons
  - click
  - pyrsistent
  - pytest
  - ipython
  - pip
  - flake8
  - black
  - pretty_errors
  - ipykernel
  - nb_conda_kernels
  - duecredit
  - ca-certificates
  - certifi
  - openssl
  - transforms3d
  - ruff
  - omegaconf
  - wandb
  - tabulate
  - gdown
  - ffmpeg
  - jupyterlab
  - mrtrix3
  - libstdcxx-ng
  - zstandard
