name: mrinr
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - simpleitk
  - pytorch[version='>=2.5']
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - scipy
  - matplotlib
  - seaborn
  - lightning
  - torchinfo
  - ubelt
  - cloudpickle
  - docker-py
  - dill
  - dipy
  - einops
  - icecream
  - ipdb
  - isort
  - ipywidgets
  - ipympl
  - jupyter
  - jupytext
  - nbstripout
  - networkx
  - numba
  - pre-commit
  - python-box
  - pytz
  - pytransform3d
  - tqdm
  - toolz
  - watermark
  - torchtriton
  - boltons
  - click
  - mrtrix3
  - pyrsistent
  - pytest
  - ipython
  - pip
  - flake8
  - black
  - pretty_errors
  - ipykernel
  - nb_conda_kernels
  - duecredit
  - ca-certificates
  - certifi
  - openssl
  - transforms3d
  - ruff
  - omegaconf
  - accelerate
  - wandb
  - tabulate
  - nccl
  - gdown
  - torch-interpol
  - pytorch-lightning
  - ffmpeg
  - jupyterlab
  - torchio
